#pragma once

#include "dsc.h"

// DeepSkillGraph — extends DeepSkillChaining to a directed graph of options and goal regions.

// PSEUDOCODE
// set of all goal regions B = { e_g1, e_g2, ...} where e_gi = epsilon ball around g_i. 

//option is defined as (I, pi, beta) where I is the initiation set, pi is the policy, and beta is the termination condition. 

// skill graph is a weighted directed graph where nodes are skills and edges represent valid transitions between skills; an edge exists only if the termination condition of the parent skill overlaps with the initiation set of the child skill. 
// G = (V, E, W)
// vertex i in V represents an option or a goal region; edge e in E exists only if the termination condition of the parent skill overlaps with the initiation set of the child skill; 
// Edge weight w_e is the accumulated reward of traversing that edge

// For a state s, V(s) is the set of vertices that the skill s maps to. 
// O(s) is the set of options that can be executed from state s
// B(s) is the set of goal regions that s can reach.
// V(s) = O(s) U B(s)
// Descendants D(v) of a vertex v is the set of vertices reachable from v.
// Ancestors A(v) of a vertex v is the set of vertices from which v is reachable via G

// Training Phase
// Expansion
// 1. Generate new goals: incentivize exploration, generate goal g such that G grows towards the largest unexplored region. Randomly sample frmo the state space ~ s_rand.
// 2. Identify nearest neighbor in G to s_rand, v_nn. (First instantiate D(s_t)= {D(v | v in V(s_t)}, where s_t is the current state of the agent.
// 3. Find v in D(s_t) that is closest to s_rand. Let v_nn = argmin_v distance(s_rand, v). distance (v, s_rand) is the maximum euclidean distance between any states in the termination set of v and s_rand
// 4. (Dijkstra's on G to find a plan to v_nn and executing the first option for T steps) x repeat until v_nn is reached. fallback to policy over options to select option to execute
// 5. From v_nn, extend the graph towards s_rand by rolling out MPC using a learned transition model that also checks for environmental constraints, for K steps, till s_mpc is reached.
// 6. Add s_mpc to set B 
// 7. This can be parallelized!

// Consolidation
// 1. Identify Goal: enumerate vertices to which there is no path from s_t. Greedily select nearest unseen vertex v_goal.
// 2. Identify subcomponents: D(s_t) = {D(v | v in V(s_t)} and A(v_goal). In subcomponents, identify pair of vertices v_d, v_a that are closest to each other
// 3. Navigate to V_d, DSC to v_a and then navigate to v_goal. 

// Adding edges to G
/*
Adding Edges to the Graph. For deterministic plans in
the skill-graph to correspond to feasible solutions in the
ground MDP, Konidaris et al. (2018) showed that any two
options o1,o2 can have an edge e1,2 between them if and
only if there is a guarantee that successful execution of
o1 will allow the agent to execute o2, i.e, e1,2 exists iff
Eo1 ⊆Io2 . To implement this rule, we store all the states in
which o1 successfully terminated and check if all of them
lie inside Io2 . Similar logic can be applied to creating edges
between options and goal regions in the graph.
*/ 

// GENERATED BY NOTEBOOKLM
// Part 1: Main DSG Algorithm
// The main loop alternates between expanding the graph into the unknown and consolidating disconnected sub-graphs.
// # INITIALIZATION
// # Initialize Graph G with start state s_0 as the first node [3, 4].
// G = Graph(nodes=[s_0], edges=[])

// # Initialize Policy over Options (pi_O) as a DQN [3, 4].
// # Initially, it only contains the Global Option o_G (primitive actions) [3, 4].
// pi_O = DeepQNetwork(outputs=[o_G]) 

// # Initialize Dynamics Model to predict next states: s_{t+1} = f(s_t, a_t) [3, 4].
// f_xi = DynamicsModel() 

// # MAIN TRAINING LOOP
// for episode in range(MAX_EPISODES):
//     state = env.reset(start_state=s_0)
    
//     # Determine Phase based on Expansion Frequency N [3, 4].
//     if episode % N == 0:
//         # Push the graph boundaries into unexplored space [5].
//         GraphExpansionPhase(state, G, f_xi, pi_O) 
//     else:
//         # Connect disjoint sub-graphs to improve connectivity [6, 7].
//         GraphConsolidationPhase(state, G, pi_O) 
        
//     # Model Training: Update dynamics model using transitions collected during the episode [3, 4].
//     f_xi.train(episode_transitions)
    
//     # Graph Update: Connect nodes if one option reliably lands in another's initiation set [3, 4].
//     for u, v in G.pairs():
//         if u.effect_set.issubset(v.initiation_set):
//             G.add_directed_edge(u, v) # Add edge u -> v in E [3, 4].
// Part 2: Graph Management Procedures
// These procedures dictate how the agent selects goals and navigates the graph.
// def GraphExpansionPhase(state, G, f_xi, pi_O):
//     # 1. Sample Goal: Randomly sample a state from the state space [5].
//     s_rand = env.sample_random_state()
    
//     # 2. Find Nearest Neighbor: Identify node v_nn in G minimizing Euclidean distance to s_rand [5].
//     v_nn = G.get_nearest_neighbor(s_rand)
    
//     # 3. Navigate to Neighbor: Move agent from current state to v_nn [5].
//     # Use the GraphPlanner if a path exists, otherwise use DSC_Policy (pi_O) [5].
//     navigate_to(v_nn, planner=G, fallback_policy=pi_O)
    
//     # 4. Extend Graph (RRT-style): If s_rand is not reachable, step into the unknown [5].
//     # Use MPC with model f_xi to plan K steps toward s_rand [5].
//     s_MPC = run_mpc_controller(f_xi, target=s_rand, steps=K)
    
//     # Create a new goal region I_new around the reached state and add to Graph [5].
//     I_new = create_goal_region(s_MPC)
//     G.add_node(I_new)

// def GraphConsolidationPhase(state, G, pi_O):
//     # 1. Identify Target: Select a node v_g in a disconnected sub-graph to maximize connectivity [6, 7].
//     v_g = G.get_closest_disconnected_node(state)
    
//     # 2. Find Connection Points [6, 7].
//     D_s = G.get_reachable_descendants(state)
//     A_vg = G.get_ancestors_reaching(v_g)
    
//     # Find pair (v_d, v_a) closest to each other across the gap [6, 7].
//     v_d, v_a = find_closest_pair(D_s, A_vg)
    
//     # 3. Bridge the Gap [6, 7].
//     navigate_to(v_d, planner=G)
    
//     # Execute DSC to train a new skill bridging the start (v_d) and target (v_a) [6, 7].
//     TrainDSC_Bridge(start=v_d, target=v_a, pi_O=pi_O)
    
//     navigate_to(v_g, planner=G)
// Part 3: Deep Skill Chaining (DSC) Details
// This section handles the execution and creation of new skills bridging the graph gaps.
// def TrainDSC_Bridge(start, target, pi_O):
//     # Initialize a new untrained option aiming for the target's initiation set
//     o_U = Option(termination_condition=target.initiation_set, policy=copy(pi_O.global_policy))
    
//     state = env.current_state
    
//     while not episode_is_done():
//         # 1. Identify Admissible Options: Check Initiation Sets [9, 13].
//         # Global option o_G is always admissible [9, 13].
//         admissible_options = [o for o in pi_O.repertoire if o.initiation_set(state) == True]
        
//         # 2. Select Option: Epsilon-greedy selection using the manager DQN [9, 13].
//         o_t = pi_O.select_option(state, admissible_options)
        
//         # 3. Execute Option [9, 13].
//         if o_t == o_G:
//             # Execute primitive action [9, 13].
//             reward, next_state, tau = execute_primitive_action()
//         else:
//             # Run internal policy until Termination Condition is met or timeout [9, 13].
//             reward, next_state, tau = execute_extended_skill(o_t)
            
//         # Store transition (s_t, o_t, r_cumulative, s_{t+tau}) in Replay Buffer [9, 13].
//         replay_buffer.store(state, o_t, reward, next_state, tau)
        
//         # 4. Train the Manager (pi_O) using SMDP Q-Learning [10, 14].
//         # Target y_t = r + (gamma^tau) * max_Q(s_{t+tau}, admissible_options_in_next_state) [10, 14].
//         pi_O.smdp_update(replay_buffer)
        
//         # 5. Monitor Gestation Period
//         if o_U.termination_condition_met(next_state):
//             o_U.record_success(state)
            
//             # Creating New Skills (Chaining) [11, 15].
//             if o_U.successes >= N:
//                 # Learn Initiation Classifier (One-Class SVM) to define region I_new [11, 15].
//                 o_U.initiation_set = train_one_class_svm(o_U.successful_start_states)
                
//                 # Add a new output neuron to the final layer of the DQN for the new option [11, 15].
//                 # Initialize the weights with the max reward seen in successful trajectories [11, 15].
//                 pi_O.add_new_skill_optimistically(o_U, max_reward=o_U.max_reward_seen)
                
//                 # The DQN now has N+1 outputs, preserving old knowledge while adding the new skill [11, 15].
//                 pi_O.repertoire.append(o_U)
//                 break 

//         state = next_state



// SUMMARY
// The main loop alternates between two phases every cfg.expansion_freq episodes:
//   Expansion    — sample s_rand, navigate to nearest graph node, run global option as MPC
//                  proxy toward s_rand, add resulting state as a new GoalRegion node.
//   Consolidation — identify closest graph node unreachable from current state, find the
//                  nearest bridgeable pair (v_d in reachable set, v_a in ancestors of v_g),
//                  navigate to v_d, train a DSC bridge toward v_a, navigate to v_g.
//
// Graph edges (u→v) exist when effect_set(u) ⊆ initiation_set(v) (Konidaris et al. 2018).
// Dijkstra over edge weights guides option selection at execution time.
//
// Unified node index convention:
//   0 .. _skills.size()-1              → skill nodes (_skills[i])
//   _skills.size() .. _totalNodes()-1  → goal region nodes (_goal_regions[i-_skills.size()])
//
// Only these methods are overridden from DeepSkillChaining:
//   train, save, load
//   _makeSkill, _shouldCreateNewOption, _validateOption, _pickOption

class DeepSkillGraph : public DeepSkillChaining
{
public:
    using Config = DeepSkillChaining::Config;

    DeepSkillGraph(std::shared_ptr<RobotBridgeTrain> robot_bridge,
                   torch::Device device,
                   AbstractedState global_goal,
                   AbstractedState global_start,
                   const std::string &pretrain_actor_path,
                   const std::string &pretrain_critic1_path,
                   const std::string &pretrain_critic2_path,
                   const std::string &scene_file,
                   Config cfg)
        : DeepSkillChaining(robot_bridge, device, global_goal, global_start,
                            pretrain_actor_path, pretrain_critic1_path, pretrain_critic2_path,
                            scene_file, cfg) {}

    DeepSkillGraph(std::shared_ptr<RobotBridgeTrain> robot_bridge,
                   torch::Device device,
                   AbstractedState global_goal,
                   AbstractedState global_start,
                   const std::string &scene_file,
                   Config cfg)
        : DeepSkillChaining(robot_bridge, device, global_goal, global_start, scene_file, cfg) {}

    int  train(int max_episodes) override;
    void save(const std::string &dir) const override;
    void load(const std::string &dir, const std::string &scene_file) override;

protected:
    // Lightweight graph node representing a reached state in unexplored space.
    // Has no policy or classifier — membership is a pure Euclidean epsilon-ball check.
    struct GoalRegion
    {
        AbstractedState center;
        float epsilon;
    };

    // Directed edge in the skill graph; weight = accumulated reward along the edge.
    struct Edge
    {
        int   from;
        int   to;
        float weight;
    };

    std::vector<GoalRegion> _goal_regions;
    std::vector<Edge>       _edges;

    // --- DSC overrides ---
    void _makeSkill(bool is_global, std::shared_ptr<Skill> parent) override;
    bool _shouldCreateNewOption() override;
    void _validateOption() override;
    std::pair<int, AbstractedState> _pickOption(bool eval) override;

    // --- graph edge management ---
    void             _updateEdges();
    std::vector<int> _dijkstraPath(int from_node) const;

private:
    // --- unified node dispatch ---
    int   _totalNodes() const;
    bool  _nodeCanStart(int node_idx, const AbstractedState &s) const;
    float _nodeDistanceToState(int node_idx, const AbstractedState &s) const;
    int   _currentNodeIdx() const;

    // --- graph queries ---
    std::vector<int>   _getReachableDescendants(int node_idx) const;
    std::vector<int>   _getAncestors(int node_idx) const;
    int                _nearestNodeToState(const AbstractedState &s) const;
    int                _closestDisconnectedNode() const;
    std::pair<int,int> _closestPair(const std::vector<int> &D,
                                    const std::vector<int> &A) const;

    // --- navigation and training primitives ---
    void            _navigateTo(int node_idx, int max_steps);
    AbstractedState _runMPCProxy(const AbstractedState &target);
    void            _trainDSCBridge(int v_a_skill_idx);

    // --- phase methods ---
    bool _graphExpansionPhase(); // returns true if a goal region was accepted (not rejected)
    void _graphConsolidationPhase();
};
